set -x
ENGINE=${1:-vllm}
# If you are using vllm<=0.6.3, you might need to set the following environment variable to avoid bugs:
# export VLLM_ATTENTION_BACKEND=XFORMERS

project_name="mix_policy_main_result"
mixup_policy=random
mix_policy_loss=expert-guided
loss_agg_mode=token-mean
experiment_name="qwen25-vl-7b-$mix_policy_loss"
export TENSORBOARD_DIR="tensorboard_log/$project_name/$experiment_name"

python3 -m src.main_ppo \
    algorithm.adv_estimator=grpo \
    algorithm.norm_adv_by_std_in_grpo=False \
    custom_reward_function.path=./src/reward_score/virl_verify.py \
    data.train_files=../DATA/vlrethink_4o/train_9k.parquet \
    data.val_files=../DATA/eval/virl_eval_geo.parquet \
    data.train_batch_size=480 \
    data.max_prompt_length=20480 \
    data.max_response_length=4096 \
    data.truncation='error' \
    data.image_key=images \
    data.shuffle=False \
    actor_rollout_ref.model.path=../huggingface/Qwen2.5-VL-7B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.warmup_style=constant \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=120 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=6 \
    actor_rollout_ref.actor.use_mix_policy_loss=$mix_policy_loss \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.loss_agg_mode=$loss_agg_mode \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=60 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.limit_images=10 \
    actor_rollout_ref.rollout.n=10 \
    actor_rollout_ref.rollout.pref_n=1 \
    actor_rollout_ref.rollout.mix_ratio=1.0 \
    actor_rollout_ref.rollout.mixup_on_policy=$mixup_policy \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=60 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    algorithm.kl_ctrl.kl_coef=0 \
    trainer.critic_warmup=0 \
    trainer.init_grpo_step=0 \
    trainer.balance_batch=True \
    trainer.logger=['console','tensorboard'] \
    trainer.project_name=$project_name \
    trainer.experiment_name=$experiment_name \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=5 \
    trainer.total_epochs=1 $@